### ISSUE TITLE
【テーブル】作成

### ISSUE THREAD

**Issue by ken-1200** [ryo-1123/django_vue_startapp#1]
#
### 背景・課題
ECサイト作成
#
### 概要

- ユーザー（商品を買う側）
一覧表示
--top画面

- 商品の詳細ページ
--カートに入れる機能
--カートの確認画面（削除と更新）
--確定画面

- ストア（商品を登録する側）
--ログイン
--商品の登録
--商品の編集（個数）
--商品の削除

#
### TASK
- [x] Storeテーブル
- [x] Itemテーブル
- [x] Userテーブル
- [x] Paymentテーブル
- [x] Roleテーブル

#
### 期限
なるはや

#
### 対象箇所・ファイル名
https://docs.google.com/spreadsheets/d/1iNCHtHYSoeKFPLw-02bqA-rb6VjHFpfPkZwMs-L_2VQ/edit?usp=sharing

#

**Comment by ryo-1123** [comment]
対応したのでクローズします。
